import type { DemoState } from "./types";

export const demoState: DemoState = {
  audit: {
    dataset: {
      source: "Official FFIEC HMDA Data Browser CSV",
      scope: "2023 Warren County, IL; action_taken in {1 originated, 3 denied}",
      rows: 230,
    },
    model: {
      version: "hmda-xgb-v0.1.0",
      backend: "sklearn-gradient-boosting",
      threshold: 0.626267,
      training: {
        rows: 230,
        positive_rate: 0.7652,
        validation_auc: 0.6477,
        threshold: 0.6263,
        cross_validation: { folds: 5, roc_auc_mean: 0.7789, roc_auc_std: 0.0648 },
        feature_policy: "Protected columns are preserved for auditing and excluded from model features.",
      },
    },
    fairness: {
      policy: {
        max_disparate_impact_deviation: 0.65,
        min_group_count: 5,
        interpretation: "Build fails when abs(1 - disparate_impact_ratio) exceeds the configured threshold.",
      },
      summary: { evaluated_slices: 6, max_disparate_impact_deviation: 0.1682, passes_bias_regression: true },
      slices: [
        {
          dimension: "race",
          group: "Race Not Available",
          reference_group: "White",
          n: 28,
          approval_rate: 0.6786,
          observed_approval_rate: 0.6786,
          statistical_parity_difference: -0.1372,
          disparate_impact_ratio: 0.8318,
          equalized_odds: { tpr_difference: 0.0135, fpr_difference: -0.2143, max_difference: 0.2143 },
          four_fifths_rule: "pass",
        },
        {
          dimension: "race",
          group: "White",
          reference_group: "White",
          n: 190,
          approval_rate: 0.8158,
          observed_approval_rate: 0.7789,
          statistical_parity_difference: 0,
          disparate_impact_ratio: 1,
          equalized_odds: { tpr_difference: 0, fpr_difference: 0, max_difference: 0 },
          four_fifths_rule: "pass",
        },
        {
          dimension: "gender",
          group: "Female",
          reference_group: "Male",
          n: 57,
          approval_rate: 0.7895,
          observed_approval_rate: 0.7719,
          statistical_parity_difference: -0.0298,
          disparate_impact_ratio: 0.9636,
          equalized_odds: { tpr_difference: 0.0299, fpr_difference: -0.1106, max_difference: 0.1106 },
          four_fifths_rule: "pass",
        },
        {
          dimension: "gender",
          group: "Joint",
          reference_group: "Male",
          n: 71,
          approval_rate: 0.7887,
          observed_approval_rate: 0.7183,
          statistical_parity_difference: -0.0305,
          disparate_impact_ratio: 0.9627,
          equalized_odds: { tpr_difference: 0.0299, fpr_difference: 0.0625, max_difference: 0.0625 },
          four_fifths_rule: "pass",
        },
        {
          dimension: "gender",
          group: "Male",
          reference_group: "Male",
          n: 83,
          approval_rate: 0.8193,
          observed_approval_rate: 0.8072,
          statistical_parity_difference: 0,
          disparate_impact_ratio: 1,
          equalized_odds: { tpr_difference: 0, fpr_difference: 0, max_difference: 0 },
          four_fifths_rule: "pass",
        },
        {
          dimension: "gender",
          group: "Sex Not Available",
          reference_group: "Male",
          n: 19,
          approval_rate: 0.7368,
          observed_approval_rate: 0.7368,
          statistical_parity_difference: -0.0824,
          disparate_impact_ratio: 0.8994,
          equalized_odds: { tpr_difference: 0.0299, fpr_difference: -0.1875, max_difference: 0.1875 },
          four_fifths_rule: "pass",
        },
      ],
    },
  },
  sampleApplicant: {
    loan_amount: 45000,
    loan_to_value_ratio: 182.62,
    income: 45,
    debt_to_income_ratio: 43,
    property_value: 25000,
    loan_term: 120,
    tract_minority_population_percent: 33.35,
    tract_to_msa_income_percentage: 82.98,
    ffiec_msa_md_median_family_income: 82300,
    loan_type: "1",
    loan_purpose: "2",
    lien_status: "1",
    occupancy_type: "1",
    preapproval: "2",
    construction_method: "1",
    derived_loan_product_type: "Conventional:First Lien",
    derived_dwelling_category: "Single Family (1-4 Units):Site-Built",
    applicant_credit_score_type: "8",
    race: "White",
    gender: "Male",
    ethnicity: "Hispanic or Latino",
  },
  samplePrediction: {
    prediction_id: "pred_demo_hmda_0001",
    decision: "deny",
    approved: false,
    probability: 0.05466,
    threshold: 0.626267,
    latency_ms: 65.85,
    model_version: "hmda-xgb-v0.1.0",
    model_backend: "sklearn-gradient-boosting",
    protected_attributes: { race: "White", gender: "Male", ethnicity: "Hispanic or Latino" },
    explanation_method: "feature_perturbation_lime_fallback",
    shap_vector: [
      { feature: "property_value", value: -0.354002, feature_value: 25000 },
      { feature: "interaction_residual", value: -0.320371, feature_value: "model interactions" },
      { feature: "loan_to_value_ratio", value: -0.124647, feature_value: 182.62 },
      { feature: "loan_purpose", value: -0.090837, feature_value: "2" },
      { feature: "loan_term", value: -0.010145, feature_value: 120 },
      { feature: "debt_to_income_ratio", value: 0.005888, feature_value: 43 },
      { feature: "income", value: 0.003474, feature_value: 45 },
      { feature: "loan_amount", value: 0.003028, feature_value: 45000 },
    ],
    top_factors: [
      { feature: "property_value", value: -0.354002, feature_value: 25000 },
      { feature: "interaction_residual", value: -0.320371, feature_value: "model interactions" },
      { feature: "loan_to_value_ratio", value: -0.124647, feature_value: 182.62 },
      { feature: "loan_purpose", value: -0.090837, feature_value: "2" },
      { feature: "loan_term", value: -0.010145, feature_value: 120 },
      { feature: "debt_to_income_ratio", value: 0.005888, feature_value: 43 },
    ],
    force_plot: {
      base_value: 0.940936,
      output_value: 0.05466,
      link: "identity_probability",
      features: [
        { feature: "property_value", value: -0.354002, feature_value: 25000 },
        { feature: "interaction_residual", value: -0.320371, feature_value: "model interactions" },
        { feature: "loan_to_value_ratio", value: -0.124647, feature_value: 182.62 },
        { feature: "loan_purpose", value: -0.090837, feature_value: "2" },
      ],
    },
  },
  counterfactual: {
    target_decision: "approve",
    original_probability: 0.05466,
    counterfactual_probability: 0.05491,
    status: "target-not-reached",
    interpretation: "The search found the closest improvement it could, but it did not cross the decision threshold.",
    changes: [
      { feature: "income", new_value: 66.12, probability: 0.05491, rationale: "Increase income" },
    ],
  },
};
